trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Davis Website/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureStaticWebAppsApiToken: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'

stages:
  - stage: Build
    displayName: 'Build and Deploy Website'
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build and Deploy Static Website'
        steps:
          - checkout: self
            displayName: 'Checkout Repository'
          
          - task: AzureStaticWebApp@0
            displayName: 'Deploy to Azure Static Web Apps'
            inputs:
              azure_static_web_apps_api_token: '$(azureStaticWebAppsApiToken)'
              repo_token: '$(System.AccessToken)'
              action: 'upload'
              app_location: '/Davis Website'
              api_location: ''
              output_location: '/Davis Website'
